package it.etoken.base.model.eosblock.entity;

import java.io.Serializable;

public class EosNode implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8310228528605230706L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_node.id
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eos_node.url
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_node.id
     *
     * @return the value of eos_node.id
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_node.id
     *
     * @param id the value for eos_node.id
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eos_node.url
     *
     * @return the value of eos_node.url
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eos_node.url
     *
     * @param url the value for eos_node.url
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }
}