package it.etoken.component.eosblock.dao.mapper;

import it.etoken.base.model.eosblock.entity.EosNode;
import it.etoken.base.model.eosblock.entity.EosNodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface EosNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eos_node
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    @SelectProvider(type=EosNodeSqlProvider.class, method="countByExample")
    long countByExample(EosNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eos_node
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    @DeleteProvider(type=EosNodeSqlProvider.class, method="deleteByExample")
    int deleteByExample(EosNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eos_node
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    @Delete({
        "delete from eos_node",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eos_node
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    @Insert({
        "insert into eos_node (id, url)",
        "values (#{id,jdbcType=INTEGER}, #{url,jdbcType=VARCHAR})"
    })
    int insert(EosNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eos_node
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    @InsertProvider(type=EosNodeSqlProvider.class, method="insertSelective")
    int insertSelective(EosNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eos_node
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    @SelectProvider(type=EosNodeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR)
    })
    List<EosNode> selectByExample(EosNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eos_node
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    @Select({
        "select",
        "id, url",
        "from eos_node",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR)
    })
    EosNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eos_node
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    @UpdateProvider(type=EosNodeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EosNode record, @Param("example") EosNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eos_node
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    @UpdateProvider(type=EosNodeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EosNode record, @Param("example") EosNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eos_node
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    @UpdateProvider(type=EosNodeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EosNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eos_node
     *
     * @mbg.generated Tue Aug 28 10:53:55 CST 2018
     */
    @Update({
        "update eos_node",
        "set url = #{url,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(EosNode record);
}